### ISSUE TITLE
which training file to use? how to organize the data?

### ISSUE THREAD

**Issue by pieterblok** [tkianai/ImageClassification.detectron2#1]
@tkianai thank you for this implementation of detectron2-classification.

I was wondering, what file should I use to train a classification on a custom dataset? The train_net.py or the train_net_buildin.py? If I understand you correctly the last one is "closer" to the standard detectron2 application. 

And what data structure does your code expect? The train folder should contain subfolders that indiciate the class_id? Similar to ImageNet? And what about the validation folder? 

And should I use the tools/make_imagenet_json.py to create the imagenet_detectron2_train.json and the imagenet_detectron2_val.json? I'm downloading the ImageNet images right now, but it takes some time :-(

Thanks in advance

**Comment by tkianai** [comment]
Hi, you can use the train_net_builtin.py(built-in trainer in detectron2) like this:

> Use default data flow in detectron2, you only need rename forward_d2 to forward, while renaming forward to forward_imgnet in imgcls/modeling/meta_arch/clsnet.py

`train_net.py` expects the formal data root as imagenet, such as:
```sh
root
    - cls1
          - 1_1.jpg
    - cls2
          - 2_1.jpg
```

`train_net_builtin.py` expects the json file as detectron2 does, you can use `make_imagenet_json.py` to creates them, more details refer to code.
